CREATE TABLE IF NOT EXISTS ScopeOfWork (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(191) NOT NULL,
    jobCategoryId INT NOT NULL,
    status ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING' NOT NULL,
    createdBy ENUM('ADMIN', 'TECHNICIAN') DEFAULT 'TECHNICIAN' NOT NULL,
    createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
    UNIQUE KEY `ScopeOfWork_name_jobCategoryId_key` (`name`, `jobCategoryId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JobScope (
    id INT AUTO_INCREMENT PRIMARY KEY,
    jobId INT NOT NULL,
    scopeOfWorkId INT NOT NULL,
    createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
    FOREIGN KEY (jobId) REFERENCES Job(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (scopeOfWorkId) REFERENCES ScopeOfWork(id) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
